services:
  app:
    image: tiptipworld-app-debug:latest
    build:
      args:
        INSTALL_XDEBUG: "true"
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
